### ISSUE TITLE
Make default settings in the game

### ISSUE THREAD

**Issue by toihirhalim** [SafdarJamal/quiz-app#17]
Hi I would like to suggest something :  
Basically in the main page, it would be easier if the select boxes have default values, so that way it would be easier for people like me to just play with default rather than spending half minute to configure that.  
And of course people can still change if they want, but I think that would save a lot of time.

**Comment by SafdarJamal** [comment]
Hey @toihirhalim, thanks for your feedback, Actually what you are suggesting's already crossed my mind since the [**v5.0**](https://github.com/SafdarJamal/quiz-app/releases/tag/v5.0.0) release. But my concern was what the default settings should be?

So here I'm asking you a little favor to answer the following questions. So I get a better understanding of it.

1. In which quiz category you want to play in by default?
2. How many questions you want in the quiz by default?
3. What default countdown time should be?

> I'm working on this feature and will be releasing it in **v5.1** in a few days.

Your feedback will be appreciated. Thanks.

**Comment by toihirhalim** [comment]
Hi @SafdarJamal thank you for responding  
so in my little experience on the app I would go as follow:  
* Category: **Any Category**  
* Number of questions: **5**  
* Difficulty : **any difficulty**  
* Question type: **any type**  
* Countdown: **2 min**  

another suggest is that of course if we can change those any time but if its already selected, the placeholder text disappear so it get a little bit hard to remember what a select is for   
  
here's an image for the situation  
![image](https://user-images.githubusercontent.com/66559721/113570968-b3cd7c00-9615-11eb-8bb1-9d48f2e6940a.png)  
  
my suggestion is to have a text before   
![image](https://user-images.githubusercontent.com/66559721/113571586-f2b00180-9616-11eb-83c1-4599f3925bea.png)  
at this way, whenever we want to change we know exactly what we're changing  
thank you for your consideration 👍

**Comment by SafdarJamal** [comment]
Hi there, thanks for this much detailed feedback. And the suggestion of adding labels on top of placeholders is good. I think it'll improve the user experience and make it more accessible.

Anyway, thank you for your time. I'm working on this feature and will be releasing it shortly.

**Comment by toihirhalim** [comment]
you're welcome 👍
