### ISSUE TITLE
Attach a custom batch of questions

### ISSUE THREAD

**Issue by minimalifestyle** [SafdarJamal/quiz-app#21]
It is possible to turn off the API call and attach a local json with custom questions with the same tree structure of opentdb?

**Comment by SafdarJamal** [comment]
Yes. It is possible. You just have to modify the [Main](https://github.com/SafdarJamal/quiz-app/blob/master/src/components/Main/index.js) component to set it to use your custom local data instead of making an API call. And make sure that your local data structure should be the same as [OpenTDB](https://opentdb.com/api_config.php)'s. Otherwise, you'll have to modify the [Quiz](https://github.com/SafdarJamal/quiz-app/blob/master/src/components/Quiz/index.js) component too.
