### ISSUE TITLE
Mock.json

### ISSUE THREAD

**Issue by jeremyjevon** [SafdarJamal/quiz-app#39]
How do I modify Main and Quiz to take in the data from "mock.json" instead of using the API?

**Comment by SafdarJamal** [comment]
To modify the Main and Quiz components to use data from "mock.json" instead of the API, follow these steps:

1. **Main Component:**

   In the Main component, you need to modify the `fetchData` function. Instead of making an API call, you should import and use the data from "mock.json". Make sure that the structure of "mock.json" matches the structure of the data you would receive from the API.

2. **Quiz Component:**

   The Quiz component does not make API calls for data; it relies on the data provided by the Main component. Since you've already set the data in the Main component, there's no need to make any changes in the Quiz component.

By following these steps, you will use the data from "mock.json" in your Main component instead of making API calls, ensuring that the data structure matches the live API data to avoid any issues. The Quiz component will continue to use the data provided by the Main component.
